/*
 * Decompiled with CFR 0.152.
 * 
 * Could not load the following classes:
 *  com.mojang.logging.LogUtils
 *  net.minecraft.SharedConstants
 *  net.minecraft.network.chat.Component
 *  net.minecraft.network.chat.MutableComponent
 *  net.minecraft.server.packs.PackLocationInfo
 *  net.minecraft.server.packs.PackSelectionConfig
 *  net.minecraft.server.packs.PackType
 *  net.minecraft.server.packs.PathPackResources$PathResourcesSupplier
 *  net.minecraft.server.packs.repository.Pack
 *  net.minecraft.server.packs.repository.Pack$Position
 *  net.minecraft.server.packs.repository.Pack$ResourcesSupplier
 *  net.minecraft.server.packs.repository.PackSource
 *  net.neoforged.api.distmarker.Dist
 *  net.neoforged.bus.api.SubscribeEvent
 *  net.neoforged.fml.common.EventBusSubscriber
 *  net.neoforged.fml.loading.FMLPaths
 *  net.neoforged.neoforge.event.AddPackFindersEvent
 *  org.slf4j.Logger
 */
package org.millenaire.client;

import com.mojang.logging.LogUtils;
import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.LinkOption;
import java.nio.file.OpenOption;
import java.nio.file.Path;
import java.util.Optional;
import java.util.function.Consumer;
import net.minecraft.SharedConstants;
import net.minecraft.network.chat.Component;
import net.minecraft.network.chat.MutableComponent;
import net.minecraft.server.packs.PackLocationInfo;
import net.minecraft.server.packs.PackSelectionConfig;
import net.minecraft.server.packs.PackType;
import net.minecraft.server.packs.PathPackResources;
import net.minecraft.server.packs.repository.Pack;
import net.minecraft.server.packs.repository.PackSource;
import net.neoforged.api.distmarker.Dist;
import net.neoforged.bus.api.SubscribeEvent;
import net.neoforged.fml.common.EventBusSubscriber;
import net.neoforged.fml.loading.FMLPaths;
import net.neoforged.neoforge.event.AddPackFindersEvent;
import org.millenaire.content.BuiltInCultures;
import org.millenaire.content.ContentDirectoryManager;
import org.millenaire.content.CustomContentIndex;
import org.millenaire.content.SubmodRoot;
import org.slf4j.Logger;

@EventBusSubscriber(modid="millenaire", value={Dist.CLIENT})
public final class CustomContentPackFinder {
    private static final Logger LOGGER = LogUtils.getLogger();

    private CustomContentPackFinder() {
    }

    @SubscribeEvent
    public static void onAddPackFinders(AddPackFindersEvent event) {
        if (event.getPackType() != PackType.CLIENT_RESOURCES) {
            return;
        }
        ContentDirectoryManager.initClient(FMLPaths.GAMEDIR.get());
        if (!ContentDirectoryManager.isInitialized()) {
            return;
        }
        CustomContentIndex index = CustomContentIndex.rebuild(BuiltInCultures.IDS);
        for (String culture : index.indexedCultures()) {
            for (SubmodRoot submod : index.rootsForCulture(culture)) {
                CustomContentPackFinder.registerPackForCulture(event, submod, culture);
            }
        }
    }

    private static void ensurePackMcmeta(Path rpDir, String packId) {
        Path metaPath = rpDir.resolve("pack.mcmeta");
        if (Files.exists(metaPath, new LinkOption[0])) {
            return;
        }
        int packFormat = SharedConstants.getCurrentVersion().getPackVersion(PackType.CLIENT_RESOURCES);
        String json = "{\n  \"_comment\": \"Auto-generated by Mill\u00e9naire \u2014 safe to delete; will be regenerated on boot.\",\n  \"pack\": {\n    \"description\": \"Mill\u00e9naire custom-content pack: " + packId + "\",\n    \"pack_format\": " + packFormat + "\n  }\n}\n";
        try {
            Files.writeString(metaPath, (CharSequence)json, StandardCharsets.UTF_8, new OpenOption[0]);
            LOGGER.info("Synthesized {} for custom-content resourcepack '{}'", (Object)metaPath, (Object)packId);
        }
        catch (IOException e) {
            LOGGER.warn("Could not synthesize {} for resourcepack '{}': {}", new Object[]{metaPath, packId, e.getMessage()});
        }
    }

    private static void registerPackForCulture(AddPackFindersEvent event, SubmodRoot submod, String culture) {
        Path rpDir = submod.root().resolve("cultures").resolve(culture).resolve("resourcepack");
        if (!Files.isDirectory(rpDir, new LinkOption[0])) {
            return;
        }
        String packId = "millenaire_custom_" + submod.name() + "_" + culture;
        MutableComponent displayName = Component.literal((String)("Mill\u00e9naire \u2014 " + submod.name() + " / " + culture));
        CustomContentPackFinder.ensurePackMcmeta(rpDir, packId);
        event.addRepositorySource(arg_0 -> CustomContentPackFinder.lambda$registerPackForCulture$0(packId, (Component)displayName, rpDir, arg_0));
    }

    private static /* synthetic */ void lambda$registerPackForCulture$0(String packId, Component displayName, Path rpDir, Consumer consumer) {
        Pack pack = Pack.readMetaAndCreate((PackLocationInfo)new PackLocationInfo(packId, displayName, PackSource.BUILT_IN, Optional.empty()), (Pack.ResourcesSupplier)new PathPackResources.PathResourcesSupplier(rpDir), (PackType)PackType.CLIENT_RESOURCES, (PackSelectionConfig)new PackSelectionConfig(true, Pack.Position.TOP, false));
        if (pack != null) {
            consumer.accept(pack);
            LOGGER.debug("Registered custom-content pack: {} ({})", (Object)packId, (Object)rpDir);
        } else {
            LOGGER.warn("Could not read pack metadata at {} \u2014 skipping", (Object)rpDir);
        }
    }
}

