/*
 * Decompiled with CFR 0.150.
 */
package org.millenaire.content.legacy;

import java.util.Set;

public final class LegacyKeySchemas {
    public static final Set<String> VILLAGER = Set.of("native_name", "alt_native_name", "alt_key", "gender", "model", "texture", "clothes", "icon", "baseheight", "malechild", "femalechild", "travelbook_display", "travelbook_held_item", "travelbook_held_item_off_hand", "travelbook_main_culture_villager", "travelbook_category", "travelbookshow", "goal", "tag", "sentencekey", "toolneededclass", "defaultweapon", "baseattackstrength", "experiencegiven", "health", "hiringcost", "requiredgood", "startinginv", "merchantstock", "collectgood", "bringbackhomegood", "itemneeded", "croptype", "soiltype", "familynamelist", "firstnamelist", "namelist", "villagerconfig", "sourceblockstate", "gatherblockstate", "resultingblockstate", "harvestblockstate", "plantblockstate", "animalkey", "helditems", "helditemsoffhand", "helditemsdestination", "helditemsoffhanddestination", "harvestitem", "bonusitem", "itemsbalance", "priority", "priorityrandom", "duration", "reoccurdelay", "range", "minimumhour", "maximumhour", "maxsimultaneousinbuilding", "maxsimultaneoustotal", "minimumtocook", "minimumfuel", "minimumpickup", "minimumavailableblocks", "max", "reputation", "price", "version", "weight", "chanceweight", "radius", "irrigation", "buildingorientation", "basespeed", "mindistance", "maxdistance", "minimumbiomevalidity", "townhallgoal", "allowrandommoves", "holdweapons", "lookatgoal", "leasure", "sprint", "collectinbuilding", "aggressiveslaughter", "isgift", "issubbuilding", "rebuildpath", "nopathstobuilding", "showtownhallsigns", "isborderbuilding");
    public static final Set<String> GOAL = Set.of("buildingtag", "requiredtag", "sentencekey", "labelkey", "sound", "tag", "icon", "itemtocook", "input", "output", "loot", "harvestitem", "bonusitem", "itemsbalance", "collect_good", "abstractedproduction", "seed", "irrigationbonuscrop", "priority", "priorityrandom", "duration", "reoccurdelay", "range", "minimumhour", "maximumhour", "maxsimultaneousinbuilding", "maxsimultaneoustotal", "minimumtocook", "minimumfuel", "minimumpickup", "minimumavailableblocks", "max", "weight", "chanceweight", "croptype", "harvestblockstate", "plantblockstate", "soiltype", "sourceblockstate", "gatherblockstate", "resultingblockstate", "animalkey", "collectinbuilding", "aggressiveslaughter", "targetposition", "targetvillagergoals", "lookatgoal", "leasure");
    public static final Set<String> SHOP = Set.of("sells", "buys", "buysoptional", "deliverto");
    public static final Set<String> VILLAGE = Set.of("name", "centre", "start", "core", "secondary", "player", "never", "customcentre", "icon", "namelist", "sellingprice", "buyingprice", "pathmaterial", "weight", "radius", "innerwallradius", "maxsimultaneousconstructions", "maxsimultaneouswallconstructions", "carriesraid", "playercontrolled", "spawnable", "biome", "type", "outerwalltype", "innerwalltype", "qualifier", "hillqualifier", "mountainqualifier", "desertqualifier", "forestqualifier", "lavaqualifier", "lakequalifier", "oceanqualifier", "brickcolourtheme", "hameau", "banner_json", "banner_pattern", "banner_basecolor", "banner_chargecolor", "banner_chargepattern", "banner_patterncolor");
    public static final Set<String> LONEBUILDING = Set.of("name", "centre", "start", "core", "secondary", "never", "player", "startingbuilding", "startsubbuilding", "weight", "radius", "mindistancefromspawn", "minimumbiomevalidity", "max", "innerwallradius", "maxsimultaneousconstructions", "maxsimultaneouswallconstructions", "carriesraid", "spawnable", "generateforplayer", "playercontrolled", "travelbook_display", "biome", "namelist", "type", "fixedorientation", "novillagewithin", "pathmaterial", "keylonebuilding", "keylonebuildinggeneratetag", "outerwalltype", "icon", "startinggood", "sellingprice", "buyingprice", "banner_json", "banner_pattern", "banner_basecolor", "banner_chargecolor", "banner_chargepattern", "banner_patterncolor");
    public static final Set<String> BUILDING_BARE = Set.of("priority", "startlevel", "pathlevel", "pathwidth", "prioritymovein", "length", "width", "areatoclear", "areatoclearlengthbefore", "areatoclearlengthafter", "areatoclearwidthbefore", "areatoclearwidthafter", "buildingorientation", "altitudeoffset", "foundationdepth", "max", "reputation", "price", "version", "irrigation", "extrasimultaneousconstructions", "extrasimultaneouswallconstructions", "mindistance", "maxdistance", "nativename", "translatedname", "shop", "subbuilding", "parentbuildingplan", "startingsubbuilding", "signs", "fixedorientation", "farfromtag", "closetotag", "tag", "cleartag", "villagetag", "requiredvillagetag", "forbiddentaginvillage", "requiredtag", "parenttag", "requiredparenttags", "exploretag", "randombrickcolour", "novillagewithin", "rebuildpath", "nopathstobuilding", "isgift", "issubbuilding", "showtownhallsigns", "travelbook_display", "male", "female", "visitor", "icon", "abstractedproduction", "startinggood", "croptype", "soiltype", "sourceblockstate", "gatherblockstate", "resultingblockstate", "harvestblockstate", "plantblockstate", "animalkey");
    public static final Set<String> QUEST = Set.of("minreputation", "chanceperhour", "maxsimultaneous", "step", "definevillager", "villager", "duration", "requiredgood", "rewardgood", "penaltygood", "rewardmoney", "rewardreputation", "penaltyreputation", "settagsuccess", "settagfailure", "settag", "cleartagsuccess", "cleartagfailure", "label_en", "label_fr", "description_en", "description_fr", "description_success_en", "description_success_fr", "description_refuse_en", "description_refuse_fr", "description_timeup_en", "description_timeup_fr", "forbiddentag", "requiredsettlementtag", "minsettlementreputation", "maxsimultaneouspervillage", "showrequiredgoods", "forbiddenplayertag", "requiredplayertag", "setplayertagsuccess", "setplayertagfailure", "clearplayertagsuccess", "clearplayertagfailure", "steprequiredplayertag", "stepforbiddenplayertag", "relationchange");
    public static final Set<String> OUT_OF_SCOPE = Set.of("iswallsegment", "outerwalltype", "wall_level_0", "wall_level_1", "wall_level_2", "wall_level_3", "wall_level_4", "wall_level_5", "isborderbuilding", "gamenamekey", "moveinpriority", "movein_priority", "custombuilding", "setglobaltagsuccess", "setglobaltagfailure", "clearglobaltagsuccess", "clearglobaltagfailure", "requiredglobaltag", "forbiddenglobaltag", "steprequiredglobaltag", "stepforbiddenglobaltag", "setactiondatasuccess", "setactiondatafailure", "bedrockbuilding");

    private LegacyKeySchemas() {
    }

    public static boolean isOutOfScope(String lowercaseKey) {
        return OUT_OF_SCOPE.contains(lowercaseKey);
    }
}

